### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zion830**
I updated how to use the transmitter!
[Related discussion](https://github.com/euphony-io/euphony/discussions/135)

### CODE REVIEW

**Review by designe — COMMENTED** [review]
Thanks for your update `README.md`
After reflecting @yeonns 's comment, let me approve it 👍

**Comment by zion830** [comment]
I applied your feedback! @yeonns

**Comment by SeonJK** [comment]
@zion830 How about modify not only source codes but also descriptions in `GETTING_STARTED.md` and `GETTING_STARTED_KR.md`? I think descriptions are still written 'Use euInitTransmit method' and 'euInitTransmit 메소드로 전송할 문장을 입력'.

**Comment by zion830** [comment]
ohhh I'm making a mistake even though it's a small change.
Thank you for letting me about that!

**Comment by zion830** [comment]
@SeonJK I applied your comment! 😀

**Review by yeonns — APPROVED** [review]
@SeonJK @zion830 Now, it looks perfect! Thank you! 💯 😄

**Review by designe — APPROVED** [review]
@SeonJK Outstanding Assist! 💯 
@zion830 Now It looks perfect to me! :)

**Pull request merged**
