### PR TITLE
Update README_Looking for job sample project

### PR DESCRIPTION
**Pull request by dlwlstks96**
## Looking_for_job

This is a sample project using the euphony library.
Enter simple resume information and transmit data using sound waves.
Converts the received sound wave into data and displays resume information.
We hope that it will be a sample project that can be used simply when looking for a job.

looking_for_job repo : https://github.com/euphony-io/looking-for-job

Co-Authored-By: Hyorin <37198145+lin9703@users.noreply.github.com>
Co-Authored-By: 6loss0m <42835988+6loss0m@users.noreply.github.com>
Co-Authored-By: dd-create <75830400+dd-create@users.noreply.github.com>

### CODE REVIEW

**Review by yeonns — COMMENTED** [review]
Nice demo app! 👍 
It would be nice if the demo application had a brief description of the app as a README.md file.

**Comment by designe** [comment]
Thanks for your contribution through the sample app development using euphony library.
@dlwlstks96 @lin9703 @dd-create @6loss0m 

When I went into the repository, 
there was no README.md. If you fill it out, I think it will be helpful for review.
And there are UI tests written in kotlin. something to look forward to. (@lin9703 )

**Comment by dlwlstks96** [comment]
I have written a basic readme and awaiting review by my team with pr.
We will also check the test code written in Kotlin.

**Review by yeonns — APPROVED** [review]
I checked your README file, which explains your amazing demo application.
And thank you for developing application. It will be helpful for users who want to use Euphony library!

**Review by designe — APPROVED** [review]
@dlwlstks96 @lin9703 @dd-create @6loss0m 
Thanks for your contribution by sample app development :)

That's simple Euphony API usage.
We can check API in [InputResumeInfo.java](https://github.com/euphony-io/looking-for-job/blob/main/app/src/main/java/com/euphonyforever/looking_for_job/InputResumeInfo.java), [MainActivity.java](https://github.com/euphony-io/looking-for-job/blob/main/app/src/main/java/com/euphonyforever/looking_for_job/MainActivity.java)

Great Job.
However, If there is a disappointment, I think it would have been better if there was an action that stops after generating a sound wave. Currently, there seems to be no way to stop it other than to kill the app.

- Github action is one of the really handy collaboration tools. It would be good to try this once when collaborating later.
- And unit test is a very important tool to check whether it works normally when developing in module unit. Even if it is difficult, you have to practice frequently. you will feel uncomfortable without it later. I think it would be good to try this too, if I have time.
- And when I look at the open issues in the repo, I see things that haven't been done yet. It doesn't seem difficult, so I think it would be good to quickly solve these problems one by one and try to close them.

OK, That's my review :)

**Pull request merged**
