### PR TITLE
Update base64Test.cpp

### PR DESCRIPTION
**Pull request by YoungSeokHong**
Co-Authored-By: JK Park <kuro11pow2@gmail.com>
Co-Authored-By: SeongHo Park <42669772+psh2849@users.noreply.github.com>
Co-Authored-By: Sujin Kim <sujinkim919@gmail.com>
Co-Authored-By: dlwlstks96 <72801465+dlwlstks96@users.noreply.github.com>
Co-Authored-By: suyeon <66951780+Jsueeee@users.noreply.github.com>
Co-Authored-By: eunzinn <88362254+eunzinn@users.noreply.github.com>
Co-Authored-By: Dohyun Lee <88221233+aiclaudev@users.noreply.github.com>
Co-Authored-By: Hyeseong Lee <satoly4@gmail.com>

Updated base64Test.cpp.😀
I fixed a test case
from
```cpp
TestParamType(std::vector<u_int8_t>{ 0xc0, 0xde, 0xba, 0x5e, 0xba, 0x11 }, "MDeLpeLoR")
```
to
```cpp
TestParamType(std::vector<u_int8_t>{ 0xc0, 0xde, 0xba, 0x5e, 0xba, 0x11 }, "wN66XroR")
```
Please do double-check! @ycs1m1yk

### CODE REVIEW

**Review by yeonns — APPROVED** [review]
Thanks to everyone who wrote the test case 👍

**Comment by Jsueeee** [comment]
Good 👍👍👍👍👍👍

**Comment by jopopcorn** [comment]
A lot of test cases are gathered! Everyone is so cool! 😆

**Comment by designe** [comment]
@YoungSeokHong @kuro11pow2 
It would be nice to include an exception case for the case where 0 is entered in #107!

**Pull request merged**
