### PR TITLE
Refactor package name of unit test

### PR DESCRIPTION
**Pull request by Kimhaedam**
## Related Issue: 
[Suggested: Update package name #234](https://github.com/euphony-io/euphony/issues/234)

- Change the package on the unit test side.
  -  `euphony.lib` -> `co.euphony`
______________________
The changed files are listed below.
 - euphony/src/test/java/co/euphony/receiver/ReceiverUnitTest.java
 - euphony/src/test/java/co/euphony/transmitter/TransmitterUnitTest.java
 - euphony/src/test/java/co/euphony/ui/viewmodel/TxRxCheckerViewModelTest.kt
 - euphony/src/test/java/co/euphony/util/EuTimerTest.kt
 - euphony/src/test/java/co/euphony/util/UtilUnitTest.java

### CODE REVIEW

**Review by yeonns — COMMENTED** [review]
@Kimhaedam Thanks for refactoring package name! Now we have consistency!
I have a one question for commits - only the last commit is related to this PR, but it contains 7 more commits before. :eyes:

**Review by designe — APPROVED** [review]
This is the package name change request from `euphony/lib` to `co.euphony`
It is going to be same with main source's package name.

it must be necessary to clean euphony repository :)

Thanks for your contribution!

**Comment by Kimhaedam** [comment]
@yeonns Yes.😔 From the time I created the PR, I saw the old commits come in together. Unfortunately, the pr started without getting rid of it. Is there a way to eliminate those seven irrelevant commits now?

**Comment by yeonns** [comment]
@Kimhaedam Maybe we can remove those commits with ```git reset --hard euphony master``` and ```git cherry-pick 7959bae```, but I think it's ok to merge current PR because there's no side effect. :smile: 
Don't worry :)

**Review by yeonns — APPROVED** [review]

**Pull request merged**
