### PR TITLE
Remove legacy stuff & Update .gitignore

### PR DESCRIPTION
**Pull request by Kimhaedam**
- Remove `.idea` folder and `.DS_Store`.
- Update `.gitignore`

Thank you for your comments on the parts need to be fixed!

### CODE REVIEW

**Review by designe — CHANGES_REQUESTED** [review]
Thanks for your kind explanation in commit message 👍 

In addition, I would like to ask you a few things below.

- Delete `.DS_Store` in `{root}/euphony/.DS_Store`
- Delete `import-summary.txt` in `{root}` : this is the extracted file through migration from eclipse. we don't need it no more :)

This is my all requests 😄

**Comment by Kimhaedam** [comment]
I've corrected the additional requests!
- 
Delete .DS_Store in euphony/euphony/
- Delete import-summary.txt

**Review by yeonns — APPROVED** [review]
Looks good! Thank you for updating ```.gitignore``` :)

**Review by designe — APPROVED** [review]
In this PR, we can remove & clean up redundant files 😄 
Thanks to resolve #159 issue!

here is euphony contributor certification!
https://promise.is/verified/euphony/certificates/Kimhaedam

**Pull request merged**
