### PR TITLE
Create PREREQUISITE.md

### PR DESCRIPTION
**Pull request by ycs1m1yk**
Update prerequisite section with more details.

Co-authored-by: hoho00 <jhoya9630@naver.com>
Co-authored-by: HACore <lhe5254@gmail.com>
Co-authored-by: YoungSeokHong <cevinlion@gmail.com>

### CODE REVIEW

**Comment by designe** [comment]
@ycs1m1yk @hoho00 @HACore @YoungSeokHong 
Co-contribution! Great! :)
But, I think the current README.md should be kept as simple as possible. 

Therefore, I think it would be better to create a new md file and provide the part you wrote.
how about PREREQUISITE.md? 

How do you think?

**Comment by ycs1m1yk** [comment]
Okay i agree with it. Then, i will create a new md file named PREREQUISITE.md. Thx for your comment!

**Comment by ycs1m1yk** [comment]
> @ycs1m1yk @hoho00 @HACore @YoungSeokHong
> Co-contribution! Great! :)
> But, I think the current README.md should be kept as simple as possible.
> 
> Therefore, I think it would be better to create a new md file and provide the part you wrote.
> how about PREREQUISITE.md?
> 
> How do you think?

  Okay i agree with that. Then, i will create a new md file named PREREQUISITE.md. Thx for your comment!

**Comment by HACore** [comment]
> @ycs1m1yk @hoho00 @HACore @YoungSeokHong
> Co-contribution! Great! :)
> But, I think the current README.md should be kept as simple as possible.
> 
> Therefore, I think it would be better to create a new md file and provide the part you wrote.
> how about PREREQUISITE.md?
> 
> How do you think?

I agree too! I think it would be good to attach a link to the PREREQUISITE.md from the README.md.

**Comment by ycs1m1yk** [comment]
I created a PREREQUISITE.md ! (bee313ffcc7560faa018fa04e245aec0c15930e4)

**Comment by YoungSeokHong** [comment]
> > @ycs1m1yk @hoho00 @HACore @YoungSeokHong
> > Co-contribution! Great! :)
> > But, I think the current README.md should be kept as simple as possible.
> > Therefore, I think it would be better to create a new md file and provide the part you wrote.
> > how about PREREQUISITE.md?
> > How do you think?
> 
> I agree too! I think it would be good to attach a link to the PREREQUISITE.md from the README.md.

Good idea. If we do that, README.md can contain larger info with a simple way!

**Comment by yeonns** [comment]
> I created a PREREQUISITE.md ! ([bee313f](https://github.com/euphony-io/euphony/commit/bee313ffcc7560faa018fa04e245aec0c15930e4))
> 
> great idea! [#28 (comment)](https://github.com/euphony-io/euphony/pull/28#issuecomment-900013117) @HACore

Good to create PREREQUISITE.md! 😄 
However, it would be better to remove the previous commits(822d822, d322c40) and apply the co-author to the last commit(bee313f).
Please try the suggestion using ```git reset --hard``` and ```cherry-pick```.
You can probably do it by running the command like below.
It may fail, so back up the PREREQUISITE.md file first and try the git command test.

```
$ git clone {ycs1m1yk_euphony}
$ git checkout -b edit_readme origin/edit_readme     
$ git reset --hard origin/master      
$ git cherry-pick bee313f
$ git commit --amend                     # modify commit message of bee313f (add co-author)
$ git push -f origin/edit_readme     # force update to edit_readme
```

**Comment by ycs1m1yk** [comment]
> > I created a PREREQUISITE.md ! ([bee313f](https://github.com/euphony-io/euphony/commit/bee313ffcc7560faa018fa04e245aec0c15930e4))
> > great idea! [#28 (comment)](https://github.com/euphony-io/euphony/pull/28#issuecomment-900013117) @HACore
> 
> Good to create PREREQUISITE.md! 😄
> However, it would be better to remove the previous commits([822d822](https://github.com/euphony-io/euphony/commit/822d82265b51246485d732f257572d7adebd405a), [d322c40](https://github.com/euphony-io/euphony/commit/d322c409df4ac47b05e6f8f092beef8abc56a2eb)) and apply the co-author to the last commit([bee313f](https://github.com/euphony-io/euphony/commit/bee313ffcc7560faa018fa04e245aec0c15930e4)).
> Please try the suggestion using `git reset --hard` and `cherry-pick`.
> You can probably do it by running the command like below.
> It may fail, so back up the PREREQUISITE.md file first and try the git command test.
> 
> ```
> $ git clone {ycs1m1yk_euphony}
> $ git checkout -b edit_readme origin/edit_readme     
> $ git reset --hard origin/master      
> $ git cherry-pick bee313f
> $ git commit --amend                     # modify commit message of bee313f (add co-author)
> $ git push -f origin/edit_readme     # force update to edit_readme, this pr commit will be changed!
> ```

Thank you for suggestion!!
I tried the command you wrote and completed successfully thanks to your detailed explanation :)

**Review by designe — COMMENTED** [review]
Awesome 👍 
Super kind description for newbies :)

There are so many images to explain.
But, most of image size and resolution are different like below.
image
image

It's good content, but the image resolution is different, could you check all image's resolution?

**Comment by designe** [comment]
image
It seems that co-contribution is not applied.

**Comment by ycs1m1yk** [comment]
> image
> It seems that co-contribution is not applied.

Oops! I will figure out what is wrong, thank you for notice!

Also, I'm going to resize the images to make the PREREQUISITE look better. https://github.com/euphony-io/euphony/pull/28#pullrequestreview-733406099

**Comment by HACore** [comment]
And how about including issue number #17 in commit so linking it with that issue?

**Comment by HACore** [comment]
For those who will see this document later, how about explicitly linking this PR page to the issue #17?
I don't have the access to set..😂

**Comment by yeonns** [comment]
> For those who will see this document later, how about explicitly linking this PR page to the issue #17?
> I don't have the access to set..😂

I did :)

**Pull request closed without merging**
